language: cpp
compiler:
	- clang
	- gcc
notifications:
	recipients:
	    - soupeaucaillou@damsy.net
	email:
		on_success: change
		on_failure: always
install:
	- sudo apt-get install -y cmake libcurl4-openssl-dev libgl1-mesa-dev libvorbis-dev libvpx-dev libtinyxml2-dev libsqlite3-dev libsdl-dev libopenal-dev libglew-dev
script: 
	- ./sac/tools/build/build-all.sh --target linux n
env:
	- BUILD_TOOL=cmake
