/*
	This file is part of Heriswap.

	@author Soupe au Caillou - Pierre-Eric Pelloux-Prayer
	@author Soupe au Caillou - Gautier Pelloux-Prayer

	Heriswap is free software: you can redistribute it and/or modify
	it under the terms of the GNU General Public License as published by
	the Free Software Foundation, version 3.

	Heriswap is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	You should have received a copy of the GNU General Public License
	along with Heriswap.  If not, see <http://www.gnu.org/licenses/>.
*/
/* DO NOT EDIT THIS FILE - it is machine generated */
#include "sac/android/sacjnilib.h"
#include "../sources/PrototypeGame.h"

class PrototypeGameThreadJNIEnvCtx : public GameThreadJNIEnvCtx {
	public:
	 
    void init(JNIEnv* pEnv, jobject assetMgr) {
	    GameThreadJNIEnvCtx::init(pEnv, assetMgr);
    }
    
    void uninit(JNIEnv* pEnv) {
		if (env == pEnv) {
		}
		GameThreadJNIEnvCtx::uninit(pEnv);
    }
};

GameHolder* GameHolder::build() {
	GameHolder* hld = new GameHolder();
	
	PrototypeGameThreadJNIEnvCtx* jniCtx = new PrototypeGameThreadJNIEnvCtx();
	hld->gameThreadJNICtx = jniCtx;
	
	hld->game = new PrototypeGame(&hld->renderThreadJNICtx.asset,
		&hld->gameThreadJNICtx->nameInput,
		&hld->gameThreadJNICtx->localize,
		&hld->gameThreadJNICtx->ad,
		&hld->gameThreadJNICtx->exitAPI);
	return hld;
};
